var _cam_x = camera_get_view_x(__view_get( e__VW.Camera, 0 ))
var _cam_y = camera_get_view_y(__view_get( e__VW.Camera, 0 ))
layer_x("Backgrounds_1", (_cam_x * 0.25))
layer_y("Backgrounds_1", (_cam_y * 0.25))
layer_x("Backgrounds_2", (_cam_x * 0.15))
layer_y("Backgrounds_2", (_cam_y * 0.15))
layer_x("Backgrounds_3", (_cam_x * 0.05))
layer_y("Backgrounds_3", (_cam_y * 0.05))
layer_x("Backgrounds_Ground1", (_cam_x * 0.25))
layer_x("Backgrounds_Ground2", (_cam_x * 0.25))
layer_x("Foreground_1", (_cam_x * 0.35))
layer_y("Foreground_1", (_cam_y * 0.35))
layer_x("Foreground_Ground1", (_cam_x * 0.35))
layer_y("Foreground_Ground1", (room_height - sprite_get_height(layer_background_get_sprite(layer_background_get_id(layer_get_id("Foreground_Ground1"))))))
